function OCPEC_problem_set = create_OCPEC_problem_set()
%UNTITLED24 Summary of this function goes here
%   Detailed explanation goes here

%
OCPEC_func_handle = {...
    @Vieira_LCS_Analytic_1;...
    @Vieira_LCS_Analytic_2;...
    @Vieira_LCS_Rel_Deg_One;...
    @Vieira_LCS_High_Dim;...
    @Vieira_LCS_Without_Penalty;...
    @Vieira_LCS_With_Penalty_1;...
    @Vieira_LCS_With_Penalty_2;...
    @Vieira_LCS_With_Penalty_3;...
    @Vieira_LCS_Control_Jump;...
    @Vieira_LCS_State_Jump_1;...
    @Vieira_LCS_State_Jump_2};

N_sequ = {100, 200, 250, 400};

%%
OCPEC_problem_set = cell(numel(OCPEC_func_handle), numel(N_sequ));
for i = 1 : numel(OCPEC_func_handle)
    for j = 1 : numel(N_sequ)
        OCPEC_i_j = OCPEC_func_handle{i}();
        OCPEC_i_j.nStages = N_sequ{j};
        OCPEC_problem_set{i, j} = OCPEC_i_j;
    end
end
%
OCPEC_problem_set = reshape(OCPEC_problem_set, [], 1);

end